name: figgy
services:
  figgy_test_solr:
    type: solr:7
    portforward: true
    core: figgy-core-test
    config:
      dir: solr/config
  figgy_test_solr_8:
    type: solr:8.4
    portforward: true
    core: figgy-8-test
    config:
      dir: solr/config
  figgy_development_solr:
    type: solr:7
    portforward: true
    core: figgy-core-dev
    config:
      dir: solr/config
  figgy_database:
    type: postgres:10
    portforward: true
proxy:
  figgy_test_solr:
    - figgy.test.solr.lndo.site:8983
  figgy_test_solr_8:
    - figgy.test.solr8.lndo.site:8983
  figgy_development_solr:
    - figgy.dev.solr.lndo.site:8983
