require: rubocop-rspec
inherit_gem:
  bixby: bixby_default.yml
AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3
  Exclude:
    - 'bin/*'
    - 'config/deploy.rb'
    - 'vendor/**/*'
    - 'valkyrie/**/*'
    - 'db/schema.rb'
    - 'spec/support/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true
Lint/ParenthesesAsGroupedExpression:
  Exclude:
    - 'spec/services/manifest_builder_spec.rb'
Metrics/AbcSize:
  Exclude:
    - 'app/services/ingest_ephemera_mods.rb'
    - 'app/services/ingest_ephemera_service.rb'
    - 'app/services/pdf_generator/cover_page_generator.rb'
    - 'app/models/concerns/linked_data/linked_ephemera_folder.rb'
    - 'app/models/ability.rb'
    - 'app/services/file_appender.rb'
    - 'app/services/pdf_generator.rb'
    - 'app/jobs/ingest_mets_job.rb'
    - 'app/jobs/ingest_intermediate_file_job.rb'
    - 'app/services/pul_metadata_services/bib_record.rb'
    - 'app/services/music_import_service.rb'
    - 'app/services/music_import_service/recording_collector.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/services/preserver.rb'
    - 'app/jobs/ingest_archival_media_bag_job.rb'
    - 'app/utils/data_seeder.rb'
    - 'app/exporters/hathi/submission_information_package.rb'
    - 'app/jobs/browse_everything_ingest_job.rb'
Metrics/BlockLength:
  Exclude:
    - '**/*.rake'
    - 'app/controllers/catalog_controller.rb'
    - 'app/models/book_workflow.rb'
    - 'config/environments/**/*'
    - 'spec/**/*'
    - 'config/initializers/*'
    - 'config/routes.rb'
    - 'lib/specs/**/*'
    - 'db/schema.rb'
    - 'app/services/pdf_generator/cover_page_generator.rb'
    - 'app/change_sets/change_set_workflow.rb'
    - 'app/resources/scanned_resources/simple_change_set.rb'
    - 'app/controllers/concerns/resource_relations.rb'
    - 'app/jobs/browse_everything_ingest_job.rb'
Metrics/ClassLength:
  Exclude:
    - 'app/change_sets/change_set.rb'
    - 'app/change_set_persisters/change_set_persister.rb'
    - 'app/resources/ephemera_folders/ephemera_folder_change_set_base.rb'
    - 'app/resources/numismatics/issues/numismatics/issue_change_set.rb'
    - 'app/resources/numismatics/issues/numismatics/issues_controller.rb'
    - 'app/change_sets/scanned_resource_change_set.rb'
    - 'app/models/ability.rb'
    - 'app/resources/ephemera_folders/ephemera_folder_decorator.rb'
    - 'app/derivative_services/raster_resource_derivative_service.rb'
    - 'app/derivative_services/vector_resource_derivative_service.rb'
    - 'app/services/geo_discovery/geoblacklight_document.rb'
    - 'app/services/geo_resource_reindexer.rb'
    - 'app/services/ingest_ephemera_service.rb'
    - 'app/services/ingest_ephemera_mods.rb'
    - 'app/utils/data_seeder.rb'
    - 'app/resources/numismatics/coins/orangelight_coin_builder.rb'
    - 'app/resources/scanned_resources/scanned_resource_decorator.rb'
    - 'app/resources/scanned_maps/scanned_map_decorator.rb'
    - 'app/models/concerns/linked_data/linked_ephemera_folder.rb'
    - 'app/services/manifest_builder/manifest_service_locator.rb'
    - 'app/services/pdf_generator/cover_page_generator.rb'
    - 'app/decorators/valkyrie/resource_decorator.rb'
    - 'app/resources/ephemera_folders/ephemera_folders_controller.rb'
    - 'app/derivative_services/jp2_derivative_service.rb'
    - 'app/services/file_appender.rb'
    - 'app/models/mets_document.rb'
    - 'app/services/bulk_ingest_service.rb'
    - 'app/models/mets_document/mods_document.rb'
    - 'app/services/pul_metadata_services/bib_record.rb'
    - 'app/resources/scanned_resources/simple_change_set.rb'
    - 'app/jobs/ingest_archival_media_bag_job.rb'
    - 'app/services/manifest_builder/manifest_service_locator_v3.rb'
    - 'app/services/manifest_builder.rb'
    - 'app/controllers/catalog_controller.rb'
    - 'app/services/music_import_service.rb'
    - 'app/services/music_import_service/recording_collector.rb'
    - 'app/services/numismatics_import_service.rb'
    - 'app/controllers/bulk_ingest_controller.rb'
    - 'app/controllers/application_controller.rb'
    - 'app/controllers/base_resource_controller.rb'
    - 'app/resources/numismatics/issues/numismatics/issue_decorator.rb'
    - 'app/resources/coins/coins_controller.rb'
    - 'app/services/preserver.rb'
    - 'app/services/preserver/importer.rb'
    - 'app/resources/collections/collections_controller.rb'
    - 'app/services/marc_record_enhancer.rb'
    - 'app/resources/numismatics/coins/numismatics/coins_controller.rb'
    - 'app/resources/numismatics/issues/numismatics/issues_controller.rb'
    - 'app/resources/numismatics/coins/numismatics/coins_controller.rb'
    - 'app/derivative_services/vips_derivative_service.rb'
    - 'app/derivative_services/thumbnail_derivative_service.rb'
    - 'app/wayfinders/base_wayfinder.rb'
Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/helpers/application_helper.rb'
    - 'app/models/concerns/linked_data/linked_resource_factory.rb'
    - 'app/services/file_appender.rb'
    - 'app/services/pdf_generator/canvas.rb'
    - 'app/jobs/ingest_intermediate_file_job.rb'
    - 'app/services/pul_metadata_services/bib_record.rb'
    - 'app/services/bulk_ingest_service.rb'
    - 'app/resources/scanned_resources/scanned_resources_controller.rb'
    - 'app/change_set_persisters/change_set_persister/apply_auth_token.rb'
    - 'config/initializers/sequel_active_support_notification.rb'
    - 'app/services/music_import_service.rb'
    - 'app/services/pdf_generator/cover_page_generator.rb'
    - 'app/services/manifest_builder.rb'
    - 'app/jobs/browse_everything_ingest_job.rb'
Metrics/LineLength:
  Exclude:
    - 'spec/views/scanned_resources/order_manager.html.erb_spec.rb'
    - 'lib/tasks/music_reserves.rake'
    - 'spec/features/playlist_spec.rb'
    - 'spec/resources/scanned_resources/scanned_resources_controller_spec.rb'
    - 'spec/views/catalog/_members_coin.html.erb_spec.rb'
    - 'spec/helpers/application_helper_spec.rb'
    - 'spec/resources/collections/collections_controller_spec.rb'
    - 'spec/models/oai/figgy/valkyrie_provider_model_spec.rb'
Metrics/MethodLength:
  Exclude:
    - 'db/migrate/**/*'
    - 'app/models/schema/common.rb'
    - 'app/models/schema/marc_relators.rb'
    - 'spec/services/manifest_builder_spec.rb'
    - 'app/services/pdf_generator/cover_page_generator.rb'
    - 'app/resources/ephemera_folders/ephemera_folder_change_set_base.rb'
    - 'app/models/concerns/linked_data/linked_ephemera_folder.rb'
    - 'app/utils/data_seeder.rb'
    - 'app/services/bulk_ingest_service.rb'
    - 'app/controllers/file_sets_controller.rb'
    - 'app/services/folder_json_importer.rb'
    - 'app/models/ability.rb'
    - 'app/models/controlled_vocabulary.rb'
    - 'app/resources/scanned_resources/simple_change_set.rb'
    - 'app/resources/numismatics/issues/numismatics/issue_change_set.rb'
    - 'app/resources/numismatics/coins/numismatics/coin_change_set.rb'
    - 'app/controllers/base_resource_controller.rb'
    - 'app/services/pdf_generator.rb'
    - 'app/services/file_appender.rb'
    - 'app/jobs/voyager_update_job.rb'
    - 'app/models/mets_document.rb'
    - 'app/jobs/ingest_intermediate_file_job.rb'
    - 'app/services/bulk_ingest_intermediate_service.rb'
    - 'app/models/remote_record.rb'
    - 'app/services/pul_metadata_services/bib_record.rb'
    - 'app/models/concerns/linked_data/linked_resource_factory.rb'
    - 'app/services/manifest_builder/canvas_rendering_builder.rb'
    - 'app/services/music_import_service.rb'
    - 'app/services/music_import_service/recording_collector.rb'
    - 'config/initializers/sequel_active_support_notification.rb'
    - 'app/services/manifest_builder.rb'
    - 'app/indexers/imported_metadata_indexer.rb'
    - 'app/controllers/concerns/resource_controller.rb'
    - 'app/models/search_builder.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/change_sets/change_set.rb'
    - 'app/resources/scanned_resources/scanned_resource_change_set.rb'
    - 'app/values/viewer_configuration.rb'
    - 'app/preserver/preserve_resource.rb'
    - 'app/services/preserver.rb'
    - 'app/services/numismatics_import_service.rb'
    - 'app/jobs/ingest_archival_media_bag_job.rb'
    - 'app/services/preserver/importer.rb'
    - 'app/jobs/bulk_update_job.rb'
    - 'app/jobs/browse_everything_ingest_job.rb'
    - 'app/controllers/application_controller.rb'
    - 'app/services/ingest_ephemera_mods.rb'
    - 'app/helpers/thumbnail_helper.rb'
    - 'app/exporters/hathi/submission_information_package.rb'
    - 'app/resources/numismatics/issues/numismatics/issues_controller.rb'
Metrics/ModuleLength:
  Exclude:
    - 'app/models/schema/marc_relators.rb'
    - 'app/controllers/concerns/resource_controller.rb'
    - 'app/helpers/application_helper.rb'
Metrics/ParameterLists:
  Exclude:
    - 'app/change_set_persisters/change_set_persister.rb'
    - 'app/jobs/ingest_folders_job.rb'
    - 'app/jobs/ingest_folder_job.rb'
    - 'app/services/music_import_service/recording_collector.rb'
    - 'app/services/music_import_service.rb'
    - 'app/services/numismatics_import_service.rb'
    - 'app/jobs/issue_import_job.rb'
    - 'app/queries/paged_all_query.rb'
    - 'spec/models/oai/figgy/valkyrie_provider_model_spec.rb'
Metrics/PerceivedComplexity:
  Exclude:
    - 'app/services/pdf_generator/canvas.rb'
    - 'app/jobs/ingest_intermediate_file_job.rb'
    - 'app/services/pul_metadata_services/bib_record.rb'
    - 'app/services/bulk_ingest_service.rb'
    - 'app/resources/scanned_resources/scanned_resources_controller.rb'
    - 'app/change_set_persisters/change_set_persister/update_auth_token.rb'
    - 'app/change_set_persisters/change_set_persister/apply_auth_token.rb'
    - 'config/initializers/sequel_active_support_notification.rb'
    - 'app/services/music_import_service.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/services/pdf_generator/cover_page_generator.rb'
    - 'app/jobs/browse_everything_ingest_job.rb'
Rails/OutputSafety:
  Exclude:
    - 'app/helpers/fixity_dashboard_helper.rb'
    - 'app/resources/**/*_decorator*'
    - 'app/validators/unique_archival_media_component_id_validator.rb'
    - 'app/controllers/users/omniauth_callbacks_controller.rb'
RSpec/AnyInstance:
  Exclude:
    - 'spec/jobs/ingest_mets_job_spec.rb'
    - 'spec/services/manifest_builder_spec.rb'
    - 'spec/services/geoblacklight_messaging_client_spec.rb'
    - 'spec/services/geoserver_messaging_client_spec.rb'
    - 'spec/services/messaging_client_spec.rb'
    - 'spec/services/orangelight_messaging_client_spec.rb'
    - 'spec/jobs/check_fixity_recursive_job_spec.rb'
    - 'spec/controllers/fixity_dashboard_controller_spec.rb'
    - 'spec/resources/archival_media_collections/archival_media_collection_change_set_spec.rb'
    - 'spec/services/voyager_updater/event_spec.rb'
    - 'spec/jobs/voyager_update_job_spec.rb'
    - 'spec/services/cloud_fixity_spec.rb'
    - 'spec/views/catalog/_members_multi_volume_work.html.erb_spec.rb'
    - 'spec/views/catalog/_resource_attributes_default.html.erb_spec.rb'
RSpec/DescribeClass:
  Exclude:
    - 'spec/abilities/**/*'
    - 'spec/features/**/*'
    - 'spec/views/**/*'
    - 'spec/routing/**/*'
    - 'spec/inputs/**/*'
    - 'spec/requests/**/*'
    - 'spec/resources/**/*routes_spec.rb'
    - 'spec/adapters/bagit/bag_roundtrip_spec.rb'
RSpec/EmptyExampleGroup:
  Exclude:
    - 'spec/models/search_builder_spec.rb'
RSpec/ExampleLength:
  Enabled: false
RSpec/FilePath:
  Exclude:
    - 'spec/registered_adapter_spec.rb'
RSpec/MessageChain:
  Exclude:
    - 'spec/resources/file_sets/file_set_decorator_spec.rb'
RSpec/MultipleExpectations:
  Enabled: false
RSpec/NestedGroups:
  Exclude:
    - 'spec/resources/scanned_resources/scanned_resources_controller_spec.rb'
    - 'spec/controllers/catalog_controller_spec.rb'
    - 'spec/controllers/simple_resources_controller_spec.rb'
    - 'spec/jobs/ingest_folders_job_spec.rb'
    - 'spec/services/manifest_builder_spec.rb'
    - 'spec/resources/playlists/playlists_controller_spec.rb'
    - 'spec/change_set_persisters/change_set_persister_spec.rb'
    - 'spec/requests/scanned_resource_spec.rb'
    - 'spec/controllers/bulk_ingest_controller_spec.rb'
    - 'spec/resources/numismatics/monograms/numismatics/monograms_controller_spec.rb'
    - 'spec/helpers/application_helper_spec.rb'
    - 'spec/requests/viewer_config_spec.rb'
    - 'spec/resources/collections/collections_controller_spec.rb'
    - 'spec/controllers/playlists_controller_spec.rb'
RSpec/VerifiedDoubles:
  Exclude:
    - 'spec/models/search_builder_spec.rb'
    - 'spec/validators/viewing_hint_validator_spec.rb'
    - 'spec/validators/viewing_direction_validator_spec.rb'
    - 'spec/validators/year_validator_spec.rb'
    - 'spec/models/user_spec.rb'
    - 'spec/derivative_services/image_derivative_service_spec.rb'
    - 'spec/derivative_services/jp2_derivative_service_spec.rb'
    - 'spec/derivative_services/vips_derivative_service_spec.rb'
    - 'spec/jobs/ingest_intermediate_file_job_spec.rb'
Naming/FileName:
  Enabled: true
  Exclude:
    - 'Gemfile'
    - '**/*.rake'
    - 'Capfile'
Lint/Void:
  Enabled: true
  Exclude:
    - 'app/derivative_services/jp2_derivative_service.rb'
Style/MethodMissingSuper:
  Exclude:
    - 'app/decorators/media_info_tracks_decorator.rb'
Style/MissingRespondToMissing:
  Exclude:
    - 'app/decorators/media_info_tracks_decorator.rb'
Naming/PredicateName:
  Exclude:
    - 'app/controllers/catalog_controller.rb'
    - 'app/models/ingestable_audio_file.rb'
Style/HashSyntax:
  Exclude:
    - 'spec/services/cdl/eligible_item_service_spec.rb'
Style/StringLiterals:
  EnforcedStyle: double_quotes
Security/MarshalLoad:
  Exclude:
    - 'app/services/music_import_service/recording_collector/marshal_cache.rb'
RSpec/ScatteredSetup:
  Exclude:
    - 'spec/resources/vector_resources/vector_resource_derivative_service_spec.rb'
    - 'spec/derivative_services/external_metadata_derivative_service_spec.rb'
Style/PreferredHashMethods:
  Exclude:
    - 'app/queries/find_ids_with_property_not_empty.rb'
    - 'app/queries/paged_all_query.rb'
Lint/Void:
  Exclude:
    # It's important that an explicit false be returned here to match the
    # expected signature, but Rubocop complains.
    - 'app/resources/templates/template_change_set.rb'
    # Triggered by a weird ImageMagick API that's necessary.
    - 'app/derivative_services/jp2_derivative_service.rb'
# We don't like postfix conditionals.
Style/IfUnlessModifier:
  Enabled: false
