require: rubocop-rspec
inherit_gem:
  bixby: bixby_default.yml
AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3
  Exclude:
    - 'bin/*'
    - 'config/deploy.rb'
    - 'vendor/**/*'
    - 'valkyrie/**/*'
    - 'db/schema.rb'
    - 'spec/support/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true
Lint/ParenthesesAsGroupedExpression:
  Exclude:
    - 'spec/services/manifest_builder_spec.rb'
Metrics/AbcSize:
  Exclude:
    - 'app/services/ingest_ephemera_service.rb'
    - 'app/services/pdf_generator/cover_page_generator.rb'
    - 'app/models/concerns/linked_data/linked_ephemera_folder.rb'
    - 'app/models/ability.rb'
    - 'app/services/file_appender.rb'
    - 'app/services/pdf_generator.rb'
    - 'app/jobs/ingest_mets_job.rb'
    - 'app/jobs/ingest_intermediate_file_job.rb'
    - 'app/services/pul_metadata_services/bib_record.rb'
    - 'app/services/music_import_service.rb'
    - 'app/services/music_import_service/recording_collector.rb'
    - 'app/controllers/bulk_ingest_controller.rb'
    - 'app/helpers/application_helper.rb'
Metrics/BlockLength:
  Exclude:
    - 'app/controllers/catalog_controller.rb'
    - 'app/models/book_workflow.rb'
    - 'config/environments/**/*'
    - 'spec/**/*'
    - 'config/initializers/*'
    - 'config/routes.rb'
    - 'lib/specs/**/*'
    - 'db/schema.rb'
    - 'lib/tasks/dev.rake'
    - 'app/services/pdf_generator/cover_page_generator.rb'
    - 'app/change_sets/change_set_workflow.rb'
    - 'lib/tasks/bulk.rake'
    - 'lib/tasks/lae.rake'
    - 'app/resources/scanned_resources/simple_change_set.rb'
    - 'app/controllers/concerns/resource_relations.rb'
    - 'lib/tasks/migrate.rake'
    - 'lib/tasks/music_reserves.rake'
    - 'lib/tasks/figgy.rake'
    - 'lib/tasks/export.rake'
Metrics/ClassLength:
  Exclude:
    - 'app/change_set_persisters/change_set_persister.rb'
    - 'app/resources/ephemera_folders/ephemera_folder_change_set_base.rb'
    - 'app/resources/numismatic_issues/numismatic_issue_change_set.rb'
    - 'app/change_sets/scanned_resource_change_set.rb'
    - 'app/models/ability.rb'
    - 'app/resources/ephemera_folders/ephemera_folder_decorator.rb'
    - 'app/derivative_services/raster_resource_derivative_service.rb'
    - 'app/derivative_services/vector_resource_derivative_service.rb'
    - 'app/services/geo_discovery/geoblacklight_document.rb'
    - 'app/services/geo_resource_reindexer.rb'
    - 'app/services/ingest_ephemera_service.rb'
    - 'app/utils/data_seeder.rb'
    - 'app/resources/scanned_resources/scanned_resource_decorator.rb'
    - 'app/resources/scanned_maps/scanned_map_decorator.rb'
    - 'app/models/concerns/linked_data/linked_ephemera_folder.rb'
    - 'app/services/manifest_builder/manifest_service_locator.rb'
    - 'app/services/pdf_generator/cover_page_generator.rb'
    - 'app/decorators/valkyrie/resource_decorator.rb'
    - 'app/resources/ephemera_folders/ephemera_folders_controller.rb'
    - 'app/derivative_services/jp2_derivative_service.rb'
    - 'app/services/file_appender.rb'
    - 'app/models/mets_document.rb'
    - 'app/services/bulk_ingest_service.rb'
    - 'app/models/mets_document/mods_document.rb'
    - 'app/services/pul_metadata_services/bib_record.rb'
    - 'app/resources/scanned_resources/simple_change_set.rb'
    - 'app/jobs/ingest_archival_media_bag_job.rb'
    - 'app/services/manifest_builder/manifest_service_locator_v3.rb'
    - 'app/services/manifest_builder.rb'
    - 'app/controllers/catalog_controller.rb'
    - 'app/services/music_import_service.rb'
    - 'app/services/music_import_service/recording_collector.rb'
    - 'app/controllers/bulk_ingest_controller.rb'
Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/helpers/application_helper.rb'
    - 'app/models/concerns/linked_data/linked_resource_factory.rb'
    - 'app/services/file_appender.rb'
    - 'app/services/pdf_generator/canvas.rb'
    - 'app/jobs/ingest_intermediate_file_job.rb'
    - 'app/services/pul_metadata_services/bib_record.rb'
    - 'app/services/bulk_ingest_service.rb'
    - 'app/resources/scanned_resources/scanned_resources_controller.rb'
    - 'app/change_set_persisters/change_set_persister/apply_auth_token.rb'
    - 'config/initializers/sequel_active_support_notification.rb'
    - 'app/services/music_import_service.rb'
Metrics/LineLength:
  Exclude:
    - 'spec/views/scanned_resources/order_manager.html.erb_spec.rb'
    - 'lib/tasks/music_reserves.rake'
    - 'spec/features/playlist_spec.rb'
    - 'spec/resources/scanned_resources/scanned_resources_controller_spec.rb'
    - 'spec/views/catalog/_members_coin.html.erb_spec.rb'
Metrics/MethodLength:
  Exclude:
    - 'db/migrate/**/*'
    - 'app/models/schema/common.rb'
    - 'app/models/schema/marc_relators.rb'
    - 'spec/services/manifest_builder_spec.rb'
    - 'app/services/pdf_generator/cover_page_generator.rb'
    - 'app/resources/ephemera_folders/ephemera_folder_change_set_base.rb'
    - 'app/models/concerns/linked_data/linked_ephemera_folder.rb'
    - 'app/utils/data_seeder.rb'
    - 'app/services/bulk_ingest_service.rb'
    - 'app/controllers/file_sets_controller.rb'
    - 'app/services/folder_json_importer.rb'
    - 'app/models/ability.rb'
    - 'app/models/controlled_vocabulary.rb'
    - 'app/resources/scanned_resources/simple_change_set.rb'
    - 'app/resources/numismatic_issues/numismatic_issue_change_set.rb'
    - 'app/resources/coins/coin_change_set.rb'
    - 'app/controllers/base_resource_controller.rb'
    - 'app/services/pdf_generator.rb'
    - 'app/services/file_appender.rb'
    - 'app/jobs/voyager_update_job.rb'
    - 'app/models/mets_document.rb'
    - 'app/jobs/ingest_intermediate_file_job.rb'
    - 'app/services/bulk_ingest_intermediate_service.rb'
    - 'app/models/remote_record.rb'
    - 'app/services/pul_metadata_services/bib_record.rb'
    - 'app/models/concerns/linked_data/linked_resource_factory.rb'
    - 'app/services/manifest_builder/canvas_rendering_builder.rb'
    - 'app/services/music_import_service.rb'
    - 'app/services/music_import_service/recording_collector.rb'
    - 'app/controllers/bulk_ingest_controller.rb'
    - 'config/initializers/sequel_active_support_notification.rb'
    - 'app/services/manifest_builder.rb'
    - 'app/indexers/imported_metadata_indexer.rb'
    - 'app/controllers/concerns/resource_controller.rb'
    - 'app/models/search_builder.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/change_sets/change_set.rb'
    - 'app/resources/scanned_resources/scanned_resource_change_set.rb'
Metrics/ModuleLength:
  Exclude:
    - 'app/models/schema/marc_relators.rb'
    - 'app/controllers/concerns/resource_controller.rb'
    - 'app/helpers/application_helper.rb'
Metrics/ParameterLists:
  Exclude:
    - 'app/change_set_persisters/change_set_persister.rb'
    - 'app/jobs/ingest_folders_job.rb'
    - 'app/jobs/ingest_folder_job.rb'
    - 'app/services/music_import_service/recording_collector.rb'
    - 'app/services/music_import_service.rb'
Metrics/PerceivedComplexity:
  Exclude:
    - 'app/services/pdf_generator/canvas.rb'
    - 'app/jobs/ingest_intermediate_file_job.rb'
    - 'app/services/pul_metadata_services/bib_record.rb'
    - 'app/services/bulk_ingest_service.rb'
    - 'app/resources/scanned_resources/scanned_resources_controller.rb'
    - 'app/change_set_persisters/change_set_persister/update_auth_token.rb'
    - 'app/change_set_persisters/change_set_persister/apply_auth_token.rb'
    - 'config/initializers/sequel_active_support_notification.rb'
    - 'app/services/music_import_service.rb'
    - 'app/helpers/application_helper.rb'
Rails/OutputSafety:
  Exclude:
    - 'app/resources/**/*_decorator*'
    - 'app/validators/unique_archival_media_component_id_validator.rb'
RSpec/AnyInstance:
  Exclude:
    - 'spec/jobs/ingest_mets_job_spec.rb'
    - 'spec/services/manifest_builder_spec.rb'
    - 'spec/services/geoblacklight_messaging_client_spec.rb'
    - 'spec/services/geoserver_messaging_client_spec.rb'
    - 'spec/services/messaging_client_spec.rb'
    - 'spec/services/orangelight_messaging_client_spec.rb'
    - 'spec/jobs/check_fixity_recursive_job_spec.rb'
    - 'spec/controllers/fixity_dashboard_controller_spec.rb'
    - 'spec/resources/archival_media_collections/archival_media_collection_change_set_spec.rb'
    - 'spec/services/voyager_updater/event_spec.rb'
    - 'spec/jobs/voyager_update_job_spec.rb'
RSpec/DescribeClass:
  Exclude:
    - 'spec/abilities/**/*'
    - 'spec/features/**/*'
    - 'spec/views/**/*'
    - 'spec/routing/**/*'
    - 'spec/inputs/**/*'
    - 'spec/requests/**/*'
    - 'spec/resources/**/*routes_spec.rb'
RSpec/EmptyExampleGroup:
  Exclude:
    - 'spec/models/search_builder_spec.rb'
RSpec/ExampleLength:
  Enabled: false
RSpec/FilePath:
  Exclude:
    - 'spec/registered_adapter_spec.rb'
RSpec/MultipleExpectations:
  Enabled: false
RSpec/NestedGroups:
  Exclude:
    - 'spec/resources/scanned_resources/scanned_resources_controller_spec.rb'
    - 'spec/controllers/catalog_controller_spec.rb'
    - 'spec/controllers/simple_resources_controller_spec.rb'
    - 'spec/jobs/ingest_folders_job_spec.rb'
    - 'spec/services/manifest_builder_spec.rb'
    - 'spec/resources/playlists/playlists_controller_spec.rb'
    - 'spec/change_set_persisters/change_set_persister_spec.rb'
    - 'spec/requests/scanned_resource_spec.rb'
    - 'spec/controllers/bulk_ingest_controller_spec.rb'
    - 'spec/resources/numismatic_monograms/numismatic_monograms_controller_spec.rb'
RSpec/VerifiedDoubles:
  Exclude:
    - 'spec/models/search_builder_spec.rb'
    - 'spec/validators/viewing_hint_validator_spec.rb'
    - 'spec/validators/viewing_direction_validator_spec.rb'
    - 'spec/validators/year_validator_spec.rb'
    - 'spec/models/user_spec.rb'
    - 'spec/derivative_services/image_derivative_service_spec.rb'
    - 'spec/derivative_services/jp2_derivative_service_spec.rb'
    - 'spec/jobs/ingest_intermediate_file_job_spec.rb'
Style/FileName:
  Enabled: true
  Exclude:
    - 'Gemfile'
    - '**/*.rake'
    - 'Capfile'
Lint/Void:
  Enabled: true
  Exclude:
    - 'app/derivative_services/jp2_derivative_service.rb'
Style/MethodMissing:
  Exclude:
    - 'app/decorators/media_info_tracks_decorator.rb'
Style/PredicateName:
  Exclude:
    - 'app/controllers/catalog_controller.rb'
    - 'app/models/ingestable_audio_file.rb'
Style/StringLiterals:
  EnforcedStyle: double_quotes
Security/MarshalLoad:
  Exclude:
    - 'app/services/music_import_service/recording_collector/marshal_cache.rb'
RSpec/ScatteredSetup:
  Exclude:
    - 'spec/resources/vector_resources/vector_resource_derivative_service_spec.rb'
    - 'spec/derivative_services/external_metadata_derivative_service_spec.rb'
