inherit_gem:
  rubocop-rails-omakase: rubocop.yml

Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBrackets: no_space

Style/FrozenStringLiteralComment:
  EnforcedStyle: never
