require: rubocop-rspec
inherit_gem:
  bixby: bixby_default.yml
AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3
  Exclude:
    - 'bin/*'
    - 'config/deploy.rb'
    - 'vendor/**/*'
    - 'valkyrie/**/*'
    - 'db/schema.rb'
    - 'spec/support/**/*'
Style/FileName:
  Enabled: true
  Exclude:
    - 'Gemfile'
    - '**/*.rake'
    - 'valhalla/Gemfile'
    - 'Capfile'
Style/PredicateName:
  Exclude:
    - 'app/controllers/catalog_controller.rb'
Rails/OutputSafety:
  Exclude:
    - 'app/decorators/**/*'
Metrics/AbcSize:
  Exclude:
    - 'app/services/pdf_generator/cover_page_generator.rb'
Metrics/BlockLength:
  Exclude:
    - 'valhalla/app/models/concerns/valhalla/ability.rb'
    - 'app/controllers/catalog_controller.rb'
    - 'app/models/book_workflow.rb'
    - 'config/environments/**/*'
    - 'spec/**/*'
    - 'config/initializers/*'
    - 'config/routes.rb'
    - 'lib/specs/**/*'
    - 'db/schema.rb'
    - 'lib/tasks/dev.rake'
    - 'app/models/plum_schema.rb'
    - 'app/services/pdf_generator/cover_page_generator.rb'
Metrics/ClassLength:
  Exclude:
    - 'app/change_set_persisters/plum_change_set_persister.rb'
Metrics/MethodLength:
  Exclude:
    - 'db/migrate/**/*'
    - 'app/models/schema/dublin_core.rb'
    - 'app/models/schema/marc_relators.rb'
    - 'app/models/schema/plum/local.rb'
    - 'spec/services/manifest_builder_spec.rb'
    - 'app/services/pdf_generator/cover_page_generator.rb'
Metrics/ModuleLength:
  Exclude:
    - 'app/models/schema/dublin_core.rb'
    - 'app/models/schema/marc_relators.rb'
RSpec/MultipleExpectations:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/DescribeClass:
  Exclude:
    - 'spec/abilities/**/*'
    - 'spec/features/**/*'
    - 'spec/views/**/*'
    - 'spec/routing/**/*'
    - 'spec/inputs/**/*'
    - 'spec/requests/**/*'
RSpec/FilePath:
  Exclude:
    - 'spec/registered_adapter_spec.rb'
RSpec/EmptyExampleGroup:
  Exclude:
    - 'spec/models/search_builder_spec.rb'
RSpec/VerifiedDoubles:
  Exclude:
    - 'spec/models/search_builder_spec.rb'
    - 'spec/validators/viewing_hint_validator_spec.rb'
    - 'spec/validators/viewing_direction_validator_spec.rb'
    - 'spec/models/user_spec.rb'
Metrics/ClassLength:
  Exclude:
    - 'app/change_set_persisters/plum_change_set_persister.rb'
Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true
