require: rubocop-rspec
inherit_gem:
  bixby: bixby_default.yml
AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3
  Exclude:
    - 'bin/*'
    - 'config/deploy.rb'
    - 'vendor/**/*'
    - 'valkyrie/**/*'
    - 'db/schema.rb'
    - 'spec/support/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
Style/FileName:
  Enabled: true
  Exclude:
    - 'Gemfile'
    - '**/*.rake'
    - 'valhalla/Gemfile'
    - 'Capfile'
Style/PredicateName:
  Exclude:
    - 'app/controllers/catalog_controller.rb'
Rails/OutputSafety:
  Exclude:
    - 'app/decorators/**/*'
Metrics/AbcSize:
  Exclude:
    - 'app/services/ingest_ephemera_service.rb'
    - 'app/services/pdf_generator/cover_page_generator.rb'
    - 'app/models/concerns/linked_data/linked_ephemera_folder.rb'
    - 'app/models/ability.rb'
Metrics/BlockLength:
  Exclude:
    - 'valhalla/app/models/concerns/valhalla/ability.rb'
    - 'app/controllers/catalog_controller.rb'
    - 'app/models/book_workflow.rb'
    - 'config/environments/**/*'
    - 'spec/**/*'
    - 'config/initializers/*'
    - 'config/routes.rb'
    - 'lib/specs/**/*'
    - 'db/schema.rb'
    - 'lib/tasks/dev.rake'
    - 'app/services/pdf_generator/cover_page_generator.rb'
    - 'valhalla/app/change_sets/valhalla/change_set_workflow.rb'
    - 'lib/tasks/bulk.rake'
    - 'lib/tasks/lae.rake'
    - 'app/change_sets/simple_resource_change_set.rb'
    - 'app/controllers/concerns/resource_relations.rb'
Metrics/ClassLength:
  Exclude:
    - 'app/change_set_persisters/plum_change_set_persister.rb'
    - 'app/change_sets/ephemera_folder_change_set_base.rb'
    - 'app/change_sets/scanned_resource_change_set.rb'
    - 'app/models/ability.rb'
    - 'app/decorators/ephemera_folder_decorator.rb'
    - 'app/services/geo_discovery/geoblacklight_document.rb'
    - 'app/services/ingest_ephemera_service.rb'
    - 'app/services/plum_importer.rb'
    - 'app/services/plum_scanned_map_importer.rb'
    - 'app/utils/data_seeder.rb'
    - 'app/decorators/scanned_resource_decorator.rb'
    - 'app/decorators/scanned_map_decorator.rb'
    - 'app/models/concerns/linked_data/linked_ephemera_folder.rb'
    - 'app/controllers/catalog_controller.rb'
    - 'app/services/manifest_builder/manifest_service_locator.rb'
    - 'app/services/pdf_generator/cover_page_generator.rb'
    - 'app/decorators/valkyrie/resource_decorator.rb'
Metrics/LineLength:
  Exclude:
    - 'spec/jobs/ingest_archival_media_bag_job_spec.rb'
    - 'app/controllers/ephemera_folders_controller.rb'
Metrics/LineLength:
  Exclude:
    - 'spec/jobs/ingest_archival_media_bag_job_spec.rb'
Metrics/MethodLength:
  Exclude:
    - 'db/migrate/**/*'
    - 'app/models/schema/common.rb'
    - 'app/models/schema/marc_relators.rb'
    - 'spec/services/manifest_builder_spec.rb'
    - 'app/services/pdf_generator/cover_page_generator.rb'
    - 'app/change_sets/ephemera_folder_change_set_base.rb'
    - 'app/models/concerns/linked_data/linked_ephemera_folder.rb'
    - 'app/utils/data_seeder.rb'
    - 'app/services/bulk_ingest_service.rb'
    - 'app/controllers/file_sets_controller.rb'
    - 'valhalla/app/controllers/concerns/valhalla/resource_controller.rb'
    - 'app/services/folder_json_importer.rb'
    - 'app/models/ability.rb'
    - 'app/models/controlled_vocabulary.rb'
    - 'app/change_sets/simple_resource_change_set.rb'
    - 'app/controllers/base_resource_controller.rb'
Metrics/ModuleLength:
  Exclude:
    - 'app/models/schema/marc_relators.rb'
    - 'valhalla/app/controllers/concerns/valhalla/resource_controller.rb'
Metrics/ParameterLists:
  Exclude:
    - 'app/change_set_persisters/plum_change_set_persister.rb'
Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/models/concerns/linked_data/linked_resource_factory.rb'
    - 'app/services/file_appender.rb'
RSpec/MultipleExpectations:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/NestedGroups:
  Exclude:
    - 'spec/controllers/scanned_resources_controller_spec.rb'
    - 'spec/controllers/catalog_controller_spec.rb'
    - 'spec/controllers/simple_resources_controller_spec.rb'
RSpec/DescribeClass:
  Exclude:
    - 'spec/abilities/**/*'
    - 'spec/features/**/*'
    - 'spec/views/**/*'
    - 'spec/routing/**/*'
    - 'spec/inputs/**/*'
    - 'spec/requests/**/*'
RSpec/FilePath:
  Exclude:
    - 'spec/registered_adapter_spec.rb'
RSpec/EmptyExampleGroup:
  Exclude:
    - 'spec/models/search_builder_spec.rb'
RSpec/VerifiedDoubles:
  Exclude:
    - 'spec/models/search_builder_spec.rb'
    - 'spec/validators/viewing_hint_validator_spec.rb'
    - 'spec/validators/viewing_direction_validator_spec.rb'
    - 'spec/models/user_spec.rb'
RSpec/AnyInstance:
  Exclude:
    - 'spec/jobs/ingest_mets_job_spec.rb'
    - 'spec/services/manifest_builder_spec.rb'
    - 'spec/services/geoblacklight_messaging_client_spec.rb'
    - 'spec/services/geoserver_messaging_client_spec.rb'
    - 'spec/services/messaging_client_spec.rb'
    - 'spec/jobs/check_fixity_recursive_job_spec.rb'
    - 'spec/controllers/fixity_dashboard_controller_spec.rb'
    - 'spec/change_sets/archival_media_collection_change_set_spec.rb'
Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true
