require: rubocop-rspec
inherit_gem:
  bixby: bixby_default.yml
AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3
  Exclude:
    - 'bin/*'
    - 'config/deploy.rb'
    - 'vendor/**/*'
    - 'valkyrie/**/*'
    - 'db/schema.rb'
    - 'spec/support/**/*'
Style/FileName:
  Enabled: true
  Exclude:
    - 'Gemfile'
    - '**/*.rake'
    - 'valhalla/Gemfile'
Style/PredicateName:
  Exclude:
    - 'app/controllers/catalog_controller.rb'
Metrics/BlockLength:
  Exclude:
    - 'app/controllers/catalog_controller.rb'
    - 'config/environments/**/*'
    - 'spec/**/*'
    - 'config/initializers/*'
    - 'config/routes.rb'
    - 'lib/specs/**/*'
    - 'db/schema.rb'
    - 'lib/tasks/dev.rake'
    - 'app/models/plum_schema.rb'
Metrics/MethodLength:
  Exclude:
    - 'db/migrate/**/*'
    - 'app/models/plum_schema.rb'
    - 'spec/services/manifest_builder_spec.rb'
Metrics/ModuleLength:
  Exclude:
    - 'app/models/plum_schema.rb'
RSpec/MultipleExpectations:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/DescribeClass:
  Exclude:
    - 'spec/abilities/**/*'
    - 'spec/features/**/*'
    - 'spec/views/**/*'
    - 'spec/routing/**/*'
    - 'spec/inputs/**/*'
    - 'spec/requests/**/*'
RSpec/FilePath:
  Exclude:
    - 'spec/registered_adapter_spec.rb'
RSpec/EmptyExampleGroup:
  Exclude:
    - 'spec/models/search_builder_spec.rb'
RSpec/VerifiedDoubles:
  Exclude:
    - 'spec/models/search_builder_spec.rb'
    - 'spec/validators/viewing_hint_validator_spec.rb'
    - 'spec/validators/viewing_direction_validator_spec.rb'
    - 'spec/models/user_spec.rb'
