# frozen_string_literal: true
source "https://rubygems.org"

gem "autoprefixer-rails"
gem "bagit"
gem "blacklight"
gem "bunny"
gem "ddtrace"
gem "devise-guests", git: "https://github.com/cbeer/devise-guests.git"
gem "flutie"
gem "honeybadger"
gem "hydra-access-controls"
gem "hydra-editor"
gem "jbuilder"
gem "jquery-rails"
gem "jquery-ui-rails", "~> 5.0"
gem "lograge"
gem "logstash-event"
gem "mediainfo", "~> 1.0"
gem "mini_magick"
gem "pg", "~> 1.0"
gem "puma"
gem "rack-cors", require: "rack/cors"
gem "rails", "5.1.6"
gem "recipient_interceptor"
gem "redis-namespace"
gem "ruby_tika_app", github: "pulibrary/ruby_tika_app"
gem "rubyzip", ">= 1.2.2"
gem "sass-rails", "~> 5.0"
gem "simple_form"
gem "sprockets", ">= 3.0.0"
gem "title"
gem "uglifier"
gem "valkyrie", "1.2.0"
gem "valkyrie-derivatives", git: "https://github.com/samvera-labs/valkyrie-derivatives.git"
gem "webpacker", "~> 3.3"

group :development do
  gem "foreman"
  gem "listen"
  gem "spring"
  gem "spring-commands-rspec"
  gem "web-console"
end

group :development, :test do
  gem "awesome_print"
  gem "bixby"
  gem "bullet"
  gem "bundler-audit", ">= 0.5.0", require: false
  gem "coveralls"
  gem "dotenv-rails"
  gem "factory_bot_rails"
  gem "pdf-reader", github: "yob/pdf-reader"
  gem "pry-byebug"
  gem "pry-rails"
  gem "rails-controller-testing"
  gem "rspec-rails", "~> 3.5"
  gem "solr_wrapper", ">= 0.3"
end

group :development, :staging do
  gem "rack-mini-profiler", require: false
end

group :test do
  gem "chromedriver-helper"
  gem "database_cleaner"
  gem "formulaic"
  gem "rspec-graphql_matchers"
  gem "selenium-webdriver"
  gem "simplecov", require: false
  gem "timecop"
  gem "webmock"
end

gem "rsolr", ">= 1.0"

gem "aasm"
gem "arabic-letter-connector"
gem "browse-everything", github: "jrgriffiniii/browse-everything", branch: "hotfix-gdrive-paging-jrgriffiniii-stable"
gem "capistrano", "~> 3.7.1"
gem "capistrano-passenger"
gem "capistrano-rails"
gem "capistrano-rails-console"
gem "coffee-rails"
gem "devise"
gem "ezid-client"
gem "faker"
gem "geo_works-derivatives", github: "pulibrary/geo_works-derivatives", tag: "v0.3.2"
gem "graphql"
gem "hydra-head"
gem "hydra-role-management"
gem "iiif_manifest", github: "samvera-labs/iiif_manifest"
gem "iso-639"
gem "jquery-datatables-rails", "~> 3.4.0"
gem "json-schema"
gem "leaflet-rails", "~> 1.3.1"
gem "marc", "~> 1.0.0"
gem "modernizr-rails"
gem "normalize-rails"
gem "omniauth-cas"
gem "openseadragon"
gem "prawn"
gem "riiif"
gem "sidekiq"
gem "string_rtl"
gem "valkyrie-sequel", github: "samvera-labs/valkyrie-sequel"
gem "whenever", "~> 0.10"

gem "graphiql-rails", group: :development
