# frozen_string_literal: true
source "https://rubygems.org"

gem "autoprefixer-rails"
gem "bagit", "~> 0.4"
gem "blacklight", "~> 7.0.0"
gem "blacklight_range_limit", "~> 7.0"
gem "bootstrap-sass", "~> 3.4"
gem "bundler", "~> 2.0"
gem "bunny"
gem "dalli"
gem "ddtrace"
gem "devise-guests", git: "https://github.com/cbeer/devise-guests.git"
gem "flutie"
gem "honeybadger"
gem "hydra-access-controls"
gem "hydra-editor"
gem "jbuilder"
gem "jquery-rails"
gem "jquery-ui-rails", "~> 5.0"
gem "lcsort", ">= 0.9.1"
gem "lograge"
gem "lograge-sql"
gem "logstash-event"
gem "mediainfo", "~> 1.0"
gem "mini_magick"
gem "pg", "~> 1.0"
gem "puma", "~> 4.3"
gem "rack", ">= 2.0.6"
gem "rack-cors", require: "rack/cors"
gem "rails", "~> 5.2.4"
gem "recipient_interceptor"
gem "redis-namespace"
gem "ruby_tika_app", github: "pulibrary/ruby_tika_app"
gem "rubyzip", ">= 1.2.2"
gem "sass-rails", "~> 5.0"
gem "simple_form"
gem "sprockets", ">= 3.7.2"
gem "sqlite3"
gem "title"
gem "uglifier"
gem "valkyrie", "~> 2.1.1"
gem "valkyrie-derivatives", git: "https://github.com/samvera-labs/valkyrie-derivatives.git"
gem "webpacker", "~> 4.0"

group :development do
  gem "benchmark-ips"
  gem "foreman"
  gem "listen"
  gem "ruby-prof"
  gem "solargraph"
  gem "spring"
  gem "spring-commands-rspec"
  gem "web-console"
end

group :development, :test do
  gem "awesome_print"
  gem "bixby"
  gem "bundler-audit", require: false
  gem "dotenv-rails"
  gem "factory_bot_rails"
  gem "pdf-reader", github: "yob/pdf-reader"
  gem "pry-byebug"
  gem "pry-rails"
  gem "rails-controller-testing"
  gem "rspec-rails", "~> 3.5"
  gem "solr_wrapper", ">= 0.3"
end

group :test do
  gem "capybara-screenshot"
  gem "database_cleaner"
  gem "formulaic"
  gem "rspec-graphql_matchers"
  gem "rspec_junit_formatter"
  gem "simplecov", require: false
  gem "timecop"
  gem "webdrivers"
  gem "webmock"
end

gem "rsolr", ">= 1.0"

gem "aasm"
gem "arabic-letter-connector"
gem "browse-everything", github: "samvera/browse-everything", branch: "2.x-stable"
gem "capistrano", "~> 3.7.1"
gem "capistrano-passenger"
gem "capistrano-rails"
gem "capistrano-rails-console"
gem "coffee-rails"
gem "damerau-levenshtein"
gem "devise", ">= 4.6.0"
gem "ezid-client"
gem "faker"
gem "filewatcher"
gem "font-awesome-rails"
gem "geo_works-derivatives", "~> 0.5.0"
gem "graphql"
gem "hydra-head"
gem "hydra-role-management"
gem "iiif_manifest", git: "https://github.com/samvera-labs/iiif_manifest"
gem "iso-639"
gem "jquery-datatables-rails", "~> 3.4.0"
gem "json-schema"
gem "leaflet-rails", "~> 1.3.1"
gem "loofah", "~> 2.3.1"
gem "m3u8"
gem "marc", "~> 1.0.0"
gem "modernizr-rails"
gem "normalize-rails"
gem "omniauth", "~> 1.9"
gem "omniauth-cas"
gem "openseadragon"
gem "prawn"
gem "riiif"
gem "sidekiq"
gem "string_rtl"
gem "tiny_tds"
gem "valkyrie-sequel", "~> 2.1.0"
gem "whenever", "~> 0.10"

gem "blacklight_iiif_search", "2.0.0"
gem "graphiql-rails", group: :development

gem "cocoon"
gem "google-cloud-pubsub"
gem "shrine-google_cloud_storage"
gem "valkyrie-shrine", "~> 0.4.0"

group :development, :staging do
  gem "rack-mini-profiler", require: false
end

gem "aws-sdk-s3"
gem "extra_extra"

gem "bootsnap", require: false
gem "oai", "~> 1.0.0"
gem "ruby-vips"
