# frozen_string_literal: true
source "https://rubygems.org"

gem "aasm"
gem "arabic-letter-connector"
gem "archivesspace-client"
gem "autoprefixer-rails"
gem "aws-sdk-s3"
gem "bagit", "~> 0.4"
gem "blacklight", "7.29.0"
gem "blacklight_iiif_search"
gem "blacklight_range_limit"
gem "bootsnap", require: false
gem "bootstrap", "~> 4.0"
gem "bootstrap_form", "~> 4.5.0"
gem "browse-everything", github: "samvera/browse-everything", branch: "2.x-stable-no-thor"
gem "bundler", "2.2.16"
gem "bunny"
gem "capistrano-passenger"
gem "capistrano-rails"
gem "capistrano-rails-console"
gem "cocoon"
gem "coffee-rails"
gem "dalli"
gem "ddtrace", "0.16.0"
gem "devise", ">= 4.6.0"
gem "devise-guests", git: "https://github.com/cbeer/devise-guests.git"
gem "dnsruby"
gem "draper"
gem "ezid-client", "1.8.0" # v1.9.0 introduces response errors in our tests/stubbing
gem "faker"
gem "filewatcher"
gem "flutie"
gem "font-awesome-rails"
gem "geoserver-publish"
gem "google-cloud-pubsub"
gem "graphiql-rails", "1.4.10", group: :development
gem "graphql", "1.8.2"
gem "honeybadger"
gem "hydra-access-controls"
gem "hydra-head"
gem "hydra-role-management"
gem "iiif_manifest", git: "https://github.com/samvera-labs/iiif_manifest"
gem "iso-639"
gem "jbuilder"
gem "jquery-datatables"
gem "jquery-rails"
gem "jquery-ui-rails", "~> 5.0"
gem "json-schema"
gem "lcsort", ">= 0.9.1"
gem "leaflet-rails"
gem "lograge"
gem "lograge-sql"
gem "logstash-event"
gem "loofah"
gem "m3u8"
gem "marc"
gem "mediainfo", "~> 1.0"
gem "mini_magick"
gem "modernizr-rails"
gem "normalize-rails"
gem "oai"
gem "omniauth"
gem "omniauth-cas"
gem "openseadragon"
gem "pg"
gem "prawn"
gem "puma"
gem "rack"
gem "rack-cors", require: "rack/cors"
gem "rails", "~> 6.0.5"
gem "recipient_interceptor"
gem "redis-namespace"
gem "reform"
gem "riiif"
gem "rsolr"
gem "ruby-progressbar"
gem "ruby-vips"
gem "ruby_tika_app", github: "pulibrary/ruby_tika_app"
gem "rubyzip"
gem "shrine-google_cloud_storage"
gem "simple_form"
gem "sprockets"
gem "sqlite3"
gem "string_rtl"
gem "title"
gem "valkyrie", "~> 3.0.0-beta.1"
gem "valkyrie-derivatives", git: "https://github.com/samvera-labs/valkyrie-derivatives.git"
gem "valkyrie-sequel", "~> 3.0.0-beta.1"
gem "valkyrie-shrine"
gem "view_component", require: "view_component/engine"
gem "webpacker", "~> 4.0"
gem "whenever", "~> 0.10"

source "https://gems.contribsys.com/" do
  gem "sidekiq-pro"
end

group :development do
  gem "benchmark-ips"
  gem "foreman"
  gem "listen"
  gem "ruby-prof"
  gem "solargraph", "~> 0.44.0"
  gem "spring"
  gem "web-console"
end

group :development, :test do
  gem "awesome_print"
  gem "bixby", "~> 3.0.0"
  gem "bundler-audit", require: false
  gem "dotenv-rails"
  gem "factory_bot_rails"
  gem "pdf-reader", github: "yob/pdf-reader"
  gem "pry-byebug"
  gem "pry-rails"
  gem "rails-controller-testing"
  gem "rspec-rails"
end

group :development, :staging do
  gem "rack-mini-profiler", require: false
end

group :test do
  gem "capybara-screenshot"
  gem "database_cleaner"
  gem "database_cleaner-sequel"
  gem "formulaic"
  gem "rspec-graphql_matchers", "0.7.1"
  gem "rspec_junit_formatter"
  gem "simplecov", require: false
  gem "timecop"
  gem "webdrivers"
  gem "webmock"
end
