# frozen_string_literal: true

##
# Defines the attributes migrated from MARC Relators
module Schema
  module MARCRelators
    extend ActiveSupport::Concern

    def self.attributes
      [
        :abridger, # http://id.loc.gov/vocabulary/relators/abr
        :actor, # http://id.loc.gov/vocabulary/relators/act
        :adapter, # http://id.loc.gov/vocabulary/relators/adp
        :addressee, # http://id.loc.gov/vocabulary/relators/rcp
        :analyst, # http://id.loc.gov/vocabulary/relators/anl
        :animator, # http://id.loc.gov/vocabulary/relators/anm
        :annotator, # http://id.loc.gov/vocabulary/relators/ann
        :appellant, # http://id.loc.gov/vocabulary/relators/apl
        :appellee, # http://id.loc.gov/vocabulary/relators/ape
        :applicant, # http://id.loc.gov/vocabulary/relators/app
        :architect, # http://id.loc.gov/vocabulary/relators/arc
        :arranger, # http://id.loc.gov/vocabulary/relators/arr
        :art_copyist, # http://id.loc.gov/vocabulary/relators/acp
        :art_director, # http://id.loc.gov/vocabulary/relators/adi
        :artist, # http://id.loc.gov/vocabulary/relators/art
        :artistic_director, # http://id.loc.gov/vocabulary/relators/ard
        :assignee, # http://id.loc.gov/vocabulary/relators/asg
        :associated_name, # http://id.loc.gov/vocabulary/relators/asn
        :attributed_name, # http://id.loc.gov/vocabulary/relators/att
        :auctioneer, # http://id.loc.gov/vocabulary/relators/auc
        :author, # http://id.loc.gov/vocabulary/relators/aut
        :author_in_quotations_or_text_abstracts, # http://id.loc.gov/vocabulary/relators/aqt
        :author_of_afterword_colophon_etc, # http://id.loc.gov/vocabulary/relators/aft
        :author_of_dialog, # http://id.loc.gov/vocabulary/relators/aud
        :author_of_introduction_etc, # http://id.loc.gov/vocabulary/relators/aui
        :autographer, # http://id.loc.gov/vocabulary/relators/ato
        :bibliographic_antecedent, # http://id.loc.gov/vocabulary/relators/ant
        :binder, # http://id.loc.gov/vocabulary/relators/bnd
        :binding_designer, # http://id.loc.gov/vocabulary/relators/bdd
        :blurb_writer, # http://id.loc.gov/vocabulary/relators/blw
        :book_designer, # http://id.loc.gov/vocabulary/relators/bkd
        :book_producer, # http://id.loc.gov/vocabulary/relators/bkp
        :bookjacket_designer, # http://id.loc.gov/vocabulary/relators/bjd
        :bookplate_designer, # http://id.loc.gov/vocabulary/relators/bpd
        :bookseller, # http://id.loc.gov/vocabulary/relators/bsl
        :braille_embosser, # http://id.loc.gov/vocabulary/relators/brl
        :broadcaster, # http://id.loc.gov/vocabulary/relators/brd
        :calligrapher, # http://id.loc.gov/vocabulary/relators/cll
        :cartographer, # http://id.loc.gov/vocabulary/relators/ctg
        :caster, # http://id.loc.gov/vocabulary/relators/cas
        :censor, # http://id.loc.gov/vocabulary/relators/cns
        :choreographer, # http://id.loc.gov/vocabulary/relators/chr
        :cinematographer, # http://id.loc.gov/vocabulary/relators/cng
        :client, # http://id.loc.gov/vocabulary/relators/cli
        :collection_registrar, # http://id.loc.gov/vocabulary/relators/cor
        :collector, # http://id.loc.gov/vocabulary/relators/col
        :collotyper, # http://id.loc.gov/vocabulary/relators/clt
        :colorist, # http://id.loc.gov/vocabulary/relators/clr
        :commentator, # http://id.loc.gov/vocabulary/relators/cmm
        :commentator_for_written_text, # http://id.loc.gov/vocabulary/relators/cwt
        :compiler, # http://id.loc.gov/vocabulary/relators/com
        :complainant, # http://id.loc.gov/vocabulary/relators/cpl
        :complainant_appellant, # http://id.loc.gov/vocabulary/relators/cpt
        :complainant_appellee, # http://id.loc.gov/vocabulary/relators/cpe
        :composer, # http://id.loc.gov/vocabulary/relators/cmp
        :compositor, # http://id.loc.gov/vocabulary/relators/cmt
        :conceptor, # http://id.loc.gov/vocabulary/relators/ccp
        :conductor, # http://id.loc.gov/vocabulary/relators/cnd
        :conservator, # http://id.loc.gov/vocabulary/relators/con
        :consultant, # http://id.loc.gov/vocabulary/relators/csl
        :consultant_to_a_project, # http://id.loc.gov/vocabulary/relators/csp
        :contestant, # http://id.loc.gov/vocabulary/relators/cos
        :contestant_appellant, # http://id.loc.gov/vocabulary/relators/cot
        :contestant_appellee, # http://id.loc.gov/vocabulary/relators/coe
        :contestee, # http://id.loc.gov/vocabulary/relators/cts
        :contestee_appellant, # http://id.loc.gov/vocabulary/relators/ctt
        :contestee_appellee, # http://id.loc.gov/vocabulary/relators/cte
        :contractor, # http://id.loc.gov/vocabulary/relators/ctr
        :copyright_claimant, # http://id.loc.gov/vocabulary/relators/cpc
        :copyright_holder, # http://id.loc.gov/vocabulary/relators/cph
        :corrector, # http://id.loc.gov/vocabulary/relators/crr
        :correspondent, # http://id.loc.gov/vocabulary/relators/crp
        :costume_designer, # http://id.loc.gov/vocabulary/relators/cst
        :court_governed, # http://id.loc.gov/vocabulary/relators/cou
        :court_reporter, # http://id.loc.gov/vocabulary/relators/crt
        :cover_designer, # http://id.loc.gov/vocabulary/relators/cov
        :curator, # http://id.loc.gov/vocabulary/relators/cur
        :dancer, # http://id.loc.gov/vocabulary/relators/dnc
        :data_contributor, # http://id.loc.gov/vocabulary/relators/dtc
        :data_manager, # http://id.loc.gov/vocabulary/relators/dtm
        :dedicatee, # http://id.loc.gov/vocabulary/relators/dte
        :dedicator, # http://id.loc.gov/vocabulary/relators/dto
        :defendant, # http://id.loc.gov/vocabulary/relators/dfd
        :defendant_appellant, # http://id.loc.gov/vocabulary/relators/dft
        :defendant_appellee, # http://id.loc.gov/vocabulary/relators/dfe
        :degree_granting_institution, # http://id.loc.gov/vocabulary/relators/dgg
        :degree_supervisor, # http://id.loc.gov/vocabulary/relators/dgs
        :delineator, # http://id.loc.gov/vocabulary/relators/dln
        :depicted, # http://id.loc.gov/vocabulary/relators/dpc
        :depositor, # http://id.loc.gov/vocabulary/relators/dpt'
        :designer, # http://id.loc.gov/vocabulary/relators/dsr
        :director, # http://id.loc.gov/vocabulary/relators/drt
        :dissertant, # http://id.loc.gov/vocabulary/relators/dis
        :distribution_place, # http://id.loc.gov/vocabulary/relators/dbp
        :distributor, # http://id.loc.gov/vocabulary/relators/dst
        :donor, # http://id.loc.gov/vocabulary/relators/dnr
        :draftsman, # http://id.loc.gov/vocabulary/relators/drm
        :dubious_author, # http://id.loc.gov/vocabulary/relators/dub
        :editor, # http://id.loc.gov/vocabulary/relators/edt
        :editor_of_compilation, # http://id.loc.gov/vocabulary/relators/edc
        :editor_of_moving_image_work, # http://id.loc.gov/vocabulary/relators/edm
        :electrician, # http://id.loc.gov/vocabulary/relators/elg
        :electrotyper, # http://id.loc.gov/vocabulary/relators/elt
        :enacting_jurisdiction, # http://id.loc.gov/vocabulary/relators/enj
        :engineer, # http://id.loc.gov/vocabulary/relators/eng
        :engraver, # http://id.loc.gov/vocabulary/relators/egr
        :etcher, # http://id.loc.gov/vocabulary/relators/etr
        :event_place, # http://id.loc.gov/vocabulary/relators/evp
        :expert, # http://id.loc.gov/vocabulary/relators/exp
        :facsimilist, # http://id.loc.gov/vocabulary/relators/fac
        :field_director, # http://id.loc.gov/vocabulary/relators/fld
        :film_distributor, # http://id.loc.gov/vocabulary/relators/fds
        :film_director, # http://id.loc.gov/vocabulary/relators/fmd
        :film_editor, # http://id.loc.gov/vocabulary/relators/flm
        :film_producer, # http://id.loc.gov/vocabulary/relators/fmp
        :filmmaker, # http://id.loc.gov/vocabulary/relators/fmk
        :first_party, # http://id.loc.gov/vocabulary/relators/fpy
        :forger, # http://id.loc.gov/vocabulary/relators/frg
        :former_owner, # http://id.loc.gov/vocabulary/relators/fmo
        :funder, # http://id.loc.gov/vocabulary/relators/fnd
        :geographic_information_specialist, # http://id.loc.gov/vocabulary/relators/gis
        :honoree, # http://id.loc.gov/vocabulary/relators/hnr
        :host, # http://id.loc.gov/vocabulary/relators/hst
        :host_institution, # http://id.loc.gov/vocabulary/relators/his
        :illuminator, # http://id.loc.gov/vocabulary/relators/ilu
        :illustrator, # http://id.loc.gov/vocabulary/relators/ill
        :inscriber, # http://id.loc.gov/vocabulary/relators/ins
        :instrumentalist, # http://id.loc.gov/vocabulary/relators/itr
        :interviewee, # http://id.loc.gov/vocabulary/relators/ive
        :interviewer, # http://id.loc.gov/vocabulary/relators/ivr
        :inventor, # http://id.loc.gov/vocabulary/relators/inv
        :issuing_body, # http://id.loc.gov/vocabulary/relators/isb
        :judge, # http://id.loc.gov/vocabulary/relators/jud
        :jurisdiction_governed, # http://id.loc.gov/vocabulary/relators/jug
        :laboratory, # http://id.loc.gov/vocabulary/relators/lbr
        :laboratory_director, # http://id.loc.gov/vocabulary/relators/ldr
        :landscape_architect, # http://id.loc.gov/vocabulary/relators/lsa
        :lead, # http://id.loc.gov/vocabulary/relators/led
        :lender, # http://id.loc.gov/vocabulary/relators/len
        :libelant, # http://id.loc.gov/vocabulary/relators/lil
        :libelant_appellant, # http://id.loc.gov/vocabulary/relators/lit
        :libelant_appellee, # http://id.loc.gov/vocabulary/relators/lie
        :libelee, # http://id.loc.gov/vocabulary/relators/lel
        :libelee_appellant, # http://id.loc.gov/vocabulary/relators/let
        :libelee_appellee, # http://id.loc.gov/vocabulary/relators/lee
        :librettist, # http://id.loc.gov/vocabulary/relators/lbt
        :licensee, # http://id.loc.gov/vocabulary/relators/lse
        :licensor, # http://id.loc.gov/vocabulary/relators/lso
        :lighting_designer, # http://id.loc.gov/vocabulary/relators/lgd
        :lithographer, # http://id.loc.gov/vocabulary/relators/ltg
        :lyricist, # http://id.loc.gov/vocabulary/relators/lyr
        :manufacture_place, # http://id.loc.gov/vocabulary/relators/mfp
        :manufacturer, # http://id.loc.gov/vocabulary/relators/mfr
        :marbler, # http://id.loc.gov/vocabulary/relators/mrb
        :markup_editor, # http://id.loc.gov/vocabulary/relators/mrk
        :medium, # http://id.loc.gov/vocabulary/relators/med
        :metadata_contact, # http://id.loc.gov/vocabulary/relators/mdc
        :metal_engraver, # http://id.loc.gov/vocabulary/relators/mte
        :minute_taker, # http://id.loc.gov/vocabulary/relators/mtk
        :moderator, # http://id.loc.gov/vocabulary/relators/mod
        :monitor, # http://id.loc.gov/vocabulary/relators/mon
        :music_copyist, # http://id.loc.gov/vocabulary/relators/mcp
        :musical_director, # http://id.loc.gov/vocabulary/relators/msd
        :musician, # http://id.loc.gov/vocabulary/relators/mus
        :narrator, # http://id.loc.gov/vocabulary/relators/nrt
        :onscreen_presenter, # http://id.loc.gov/vocabulary/relators/osp
        :opponent, # http://id.loc.gov/vocabulary/relators/opn
        :organizer, # http://id.loc.gov/vocabulary/relators/orm
        :originator, # http://id.loc.gov/vocabulary/relators/org
        :other, # http://id.loc.gov/vocabulary/relators/oth
        :owner, # http://id.loc.gov/vocabulary/relators/own
        :panelist, # http://id.loc.gov/vocabulary/relators/pan
        :papermaker, # http://id.loc.gov/vocabulary/relators/ppm
        :patent_applicant, # http://id.loc.gov/vocabulary/relators/pta
        :patent_holder, # http://id.loc.gov/vocabulary/relators/pth
        :patron, # http://id.loc.gov/vocabulary/relators/pat
        :performer, # http://id.loc.gov/vocabulary/relators/prf
        :permitting_agency, # http://id.loc.gov/vocabulary/relators/pma
        :photographer, # http://id.loc.gov/vocabulary/relators/pht
        :plaintiff, # http://id.loc.gov/vocabulary/relators/ptf
        :plaintiff_appellant, # http://id.loc.gov/vocabulary/relators/ptt
        :plaintiff_appellee, # http://id.loc.gov/vocabulary/relators/pte
        :platemaker, # http://id.loc.gov/vocabulary/relators/plt
        :praeses, # http://id.loc.gov/vocabulary/relators/pra
        :presenter, # http://id.loc.gov/vocabulary/relators/pre
        :printer, # http://id.loc.gov/vocabulary/relators/prt
        :printer_of_plates, # http://id.loc.gov/vocabulary/relators/pop
        :printmaker, # http://id.loc.gov/vocabulary/relators/prm
        :process_contact, # http://id.loc.gov/vocabulary/relators/prc
        :producer, # http://id.loc.gov/vocabulary/relators/pro
        :production_company, # http://id.loc.gov/vocabulary/relators/prn
        :production_designer, # http://id.loc.gov/vocabulary/relators/prs
        :production_manager, # http://id.loc.gov/vocabulary/relators/pmn
        :production_personnel, # http://id.loc.gov/vocabulary/relators/prd
        :production_place, # http://id.loc.gov/vocabulary/relators/prp
        :programmer, # http://id.loc.gov/vocabulary/relators/prg
        :project_director, # http://id.loc.gov/vocabulary/relators/pdr
        :proofreader, # http://id.loc.gov/vocabulary/relators/pfr
        :provider, # http://id.loc.gov/vocabulary/relators/prv
        :publication_place, # http://id.loc.gov/vocabulary/relators/pup
        :publishing_director, # http://id.loc.gov/vocabulary/relators/pbd
        :puppeteer, # http://id.loc.gov/vocabulary/relators/ppt
        :radio_director, # http://id.loc.gov/vocabulary/relators/rdd
        :radio_producer, # http://id.loc.gov/vocabulary/relators/rpc
        :recording_engineer, # http://id.loc.gov/vocabulary/relators/rce
        :recordist, # http://id.loc.gov/vocabulary/relators/rcd
        :redaktor, # http://id.loc.gov/vocabulary/relators/red
        :renderer, # http://id.loc.gov/vocabulary/relators/ren
        :reporter, # http://id.loc.gov/vocabulary/relators/rpt
        :marc_repository, # http://id.loc.gov/vocabulary/relators/rps
        :research_team_head, # http://id.loc.gov/vocabulary/relators/rth
        :research_team_member, # http://id.loc.gov/vocabulary/relators/rtm
        :researcher, # http://id.loc.gov/vocabulary/relators/res
        :respondent, # http://id.loc.gov/vocabulary/relators/rsp
        :respondent_appellant, # http://id.loc.gov/vocabulary/relators/rst
        :respondent_appellee, # http://id.loc.gov/vocabulary/relators/rse
        :responsible_party, # http://id.loc.gov/vocabulary/relators/rpy
        :restager, # http://id.loc.gov/vocabulary/relators/rsg
        :restorationist, # http://id.loc.gov/vocabulary/relators/rsr
        :reviewer, # http://id.loc.gov/vocabulary/relators/rev
        :rubricator, # http://id.loc.gov/vocabulary/relators/rbr
        :scenarist, # http://id.loc.gov/vocabulary/relators/sce
        :scientific_advisor, # http://id.loc.gov/vocabulary/relators/sad
        :screenwriter, # http://id.loc.gov/vocabulary/relators/aus
        :scribe, # http://id.loc.gov/vocabulary/relators/scr
        :sculptor, # http://id.loc.gov/vocabulary/relators/scl
        :second_party, # http://id.loc.gov/vocabulary/relators/spy
        :secretary, # http://id.loc.gov/vocabulary/relators/sec
        :seller, # http://id.loc.gov/vocabulary/relators/sll
        :set_designer, # http://id.loc.gov/vocabulary/relators/std
        :setting, # http://id.loc.gov/vocabulary/relators/stg
        :signer, # http://id.loc.gov/vocabulary/relators/sgn
        :singer, # http://id.loc.gov/vocabulary/relators/sng
        :sound_designer, # http://id.loc.gov/vocabulary/relators/sds
        :speaker, # http://id.loc.gov/vocabulary/relators/spk
        :sponsor, # http://id.loc.gov/vocabulary/relators/spn
        :stage_director, # http://id.loc.gov/vocabulary/relators/sgd
        :stage_manager, # http://id.loc.gov/vocabulary/relators/stm
        :standards_body, # http://id.loc.gov/vocabulary/relators/stn
        :stereotyper, # http://id.loc.gov/vocabulary/relators/str
        :storyteller, # http://id.loc.gov/vocabulary/relators/stl
        :supporting_host, # http://id.loc.gov/vocabulary/relators/sht
        :surveyor, # http://id.loc.gov/vocabulary/relators/srv
        :teacher, # http://id.loc.gov/vocabulary/relators/tch
        :technical_director, # http://id.loc.gov/vocabulary/relators/tcd
        :television_director, # http://id.loc.gov/vocabulary/relators/tld
        :television_producer, # http://id.loc.gov/vocabulary/relators/tlp
        :thesis_advisor, # http://id.loc.gov/vocabulary/relators/ths
        :transcriber, # http://id.loc.gov/vocabulary/relators/trc
        :translator, # http://id.loc.gov/vocabulary/relators/trl
        :type_designer, # http://id.loc.gov/vocabulary/relators/tyd
        :typographer, # http://id.loc.gov/vocabulary/relators/tyg
        :university_place, # http://id.loc.gov/vocabulary/relators/uvp
        :videographer, # http://id.loc.gov/vocabulary/relators/vdg
        :voice_actor, # http://id.loc.gov/vocabulary/relators/vac
        :witness, # http://id.loc.gov/vocabulary/relators/wit
        :wood_engraver, # http://id.loc.gov/vocabulary/relators/wde
        :woodcutter, # http://id.loc.gov/vocabulary/relators/wdc
        :writer_of_accompanying_material, # http://id.loc.gov/vocabulary/relators/wam
        :writer_of_added_commentary, # http://id.loc.gov/vocabulary/relators/wac
        :writer_of_added_text, # http://id.loc.gov/vocabulary/relators/wat
        :writer_of_added_lyrics, # http://id.loc.gov/vocabulary/relators/wal
        :writer_of_supplementary_textual_content, # http://id.loc.gov/vocabulary/relators/wst
        :writer_of_introduction, # http://id.loc.gov/vocabulary/relators/win
        :writer_of_preface # http://id.loc.gov/vocabulary/relators/wpr
      ]
    end

    included do
      MARCRelators.attributes.each do |field|
        attribute field
      end
    end
  end
end
