:terms:
  - :value: "harmful_content"
    :label: "Harmful Content"
    :heading: "stuff"
    :definition: "stuff"
  - :value: "explicit_content"
    :label: "Explicit Content"
    :heading: "stuff"
    :definition: "stuff"
  - :value: "senior_thesis"
    :label: "Senior Thesis"
    :heading: "Terms and Conditions for Using Princeton University Senior Theses"
    :definition: >-
      The copyright and related rights status of this Item has not been evaluated.

      <br/>Please refer to the organization that has made the Item available for more
      information.

      <br/>You are free to use this Item in any way that is permitted by the
      copyright and related rights legislation that applies to your use.
