# You can find the UI elements for these in config/locales/en.yml under the
# notices key.
:terms:
  - :value: "harmful_content"
    :label: "Harmful Content"
  - :value: "explicit_content"
    :label: "Explicit Content"
  - :value: "senior_thesis"
    :label: "Senior Thesis"
