development:
  adapter: redis
  host: <%= ENV["lando_redis_conn_host"] || "localhost" %>
  port: <%= ENV["lando_redis_conn_port"] || 6379 %>
  db: 0

test:
  adapter: async

production: &production
  adapter: redis
  host: <%= ENV['FIGGY_REDIS_URL'] || 'localhost' %>
  port: <%= ENV['FIGGY_REDIS_PORT'] || '6379' %>
  db: <%= ENV['FIGGY_REDIS_DB'] || 0 %>

staging:
  <<: *production
