development:
  host: <%= ENV["lando_redis_conn_host"] || "localhost" %>
  port: <%= ENV["lando_redis_conn_port"] || 6379 %>
  db: 0
test:
  host: <%= ENV["lando_redis_conn_host"] || "localhost" %>
  port: <%= ENV["lando_redis_conn_port"] || 6379 %>
  db: 0
production: &production
  host: <%= ENV['FIGGY_REDIS_URL'] || 'localhost' %>
  port: <%= ENV['FIGGY_REDIS_PORT'] || '6379' %>
  db: <%= ENV['FIGGY_REDIS_DB'] || 0 %>
staging:
  name: 'redis-staging'
  password: <%= ENV['FIGGY_REDIS_PASSWORD'] %>
  sentinel_password: <%= ENV['FIGGY_REDIS_PASSWORD'] %>
  sentinels:
    - host: "nomad-client-staging4.lib.princeton.edu"
      port: 26379
      db: <%= ENV['FIGGY_REDIS_DB'] || 0 %>
    - host: "dpul-collections-staging1.lib.princeton.edu"
      port: 26379
      db: <%= ENV['FIGGY_REDIS_DB'] || 0 %>
    - host: "dpul-collections-staging2.lib.princeton.edu"
      port: 26379
      db: <%= ENV['FIGGY_REDIS_DB'] || 0 %>
