default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

development:
  <<: *default

test:
  <<: *default
  secret_key_base: "asdf9hasdf89hasd9f8has9dfnasidfbalfblsfd"

staging:
  <<: *default

production:
  <<: *default
