production: &defaults
  user: <%= ENV["SVN_USER"] %>
  pass: <%= ENV["SVN_PASS"] %>
  url: <%= ENV["SVN_URL"] %>
  dir: <%= ENV["SVN_DIR"] %>

staging:
  <<: *defaults

development:
  <<: *defaults

test:
  user: "tester"
  pass: "testing"
  url: "http://example.com/svn"
  dir: <%= Rails.root.join("tmp", "svn") %>
