# frozen_string_literal: true

require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe AuthTokensController, type: :controller do
  # This should return the minimal set of attributes required to create a valid
  # AuthToken. As you add validations to AuthToken, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    {group: ["admin"], label: "Admin"}
  end
  let(:invalid_attributes) do
    {group: ["Invalid"], label: ""}
  end

  let(:user) { FactoryBot.create(:admin) }
  before do
    sign_in user
  end

  describe "GET #index" do
    it "returns a success response" do
      AuthToken.create! valid_attributes
      get :index, params: {}
      expect(response).to be_successful
    end
  end

  describe "GET #show" do
    it "returns a success response" do
      auth_token = AuthToken.create! valid_attributes
      get :show, params: {id: auth_token.to_param}
      expect(response).to be_successful
    end
  end

  describe "GET #new" do
    it "returns a success response" do
      get :new, params: {}
      expect(response).to be_successful
    end
  end

  describe "GET #edit" do
    it "returns a success response" do
      auth_token = AuthToken.create! valid_attributes
      get :edit, params: {id: auth_token.to_param}
      expect(response).to be_successful
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new AuthToken" do
        expect do
          post :create, params: {auth_token: valid_attributes}
        end.to change(AuthToken, :count).by(1)
      end

      it "redirects to the created auth_token" do
        post :create, params: {auth_token: valid_attributes}
        expect(response).to redirect_to(AuthToken.last)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'new' template)" do
        post :create, params: {auth_token: invalid_attributes}
        expect(response).to be_successful
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) do
        {label: "New Label", group: ["staff"]}
      end

      it "updates the requested auth_token" do
        auth_token = AuthToken.create! valid_attributes
        put :update, params: {id: auth_token.to_param, auth_token: new_attributes}
        auth_token.reload
        expect(auth_token.label).to eq "New Label"
        expect(auth_token.group).to eq ["staff"]
      end

      it "redirects to the auth_token" do
        auth_token = AuthToken.create! valid_attributes
        put :update, params: {id: auth_token.to_param, auth_token: valid_attributes}
        expect(response).to redirect_to(auth_token)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'edit' template)" do
        auth_token = AuthToken.create! valid_attributes
        put :update, params: {id: auth_token.to_param, auth_token: invalid_attributes}
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested auth_token" do
      auth_token = AuthToken.create! valid_attributes
      expect do
        delete :destroy, params: {id: auth_token.to_param}
      end.to change(AuthToken, :count).by(-1)
    end

    it "redirects to the auth_tokens list" do
      auth_token = AuthToken.create! valid_attributes
      delete :destroy, params: {id: auth_token.to_param}
      expect(response).to redirect_to(auth_tokens_url)
    end
  end
end
